title: Doteur wiki
email: loic.labeye@tutanota.de
description: >- # this means to ignore newlines until "baseurl:"
        Doteur is an awesome tool to transform your SQL schemas into DOT files usable by GraphViz. It will help you to make good looking schemas in few seconds.
baseurl: "/doteur" # the subpath of your site, e.g. /blog
url: "https://nag763.github.io"
github_username:  nag763
github_repo: doteur

markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
url: https://nag763.github.io
domain: nag763.github.io
destination: ../docs
