[package]
name = "doteur_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
log = "0.4.14"
itertools = "0.10.3"
mysql = { version="21.0.2", optional=true}
rusqlite = { version="0.26.3", optional=true}

[features]
mysql_addons = ["mysql"]
sqlite_addons = ["rusqlite"]
